치지직:
  탬탬버린:
    식별자: a7e175625fdea5a7d98428302b7aa57f
    마크닉네임: chamcham2
  아이리칸나:
    식별자: f722959d1b8e651bd56209b343932c01
    마크닉네임: kanna
아프리카:
  앵보:
    식별자: qweasd3456
    마크닉네임: angryboy

랜덤 보상: false
후원 보상:
  0:
    - say 가격을 0원으로 쓰면 설정 안된 가격을 의미합니다.
    - say 예를 들어 1000원, 3000원 이외 후원들은 모두 이 명령어가 실행됩니다.
    - say 물론 0원을 설정해놓지 않으면 정해놓은 가격 이외 후원은 무시됩니다.
  1000:
    - say hi
    - time set 0
  3000:
    - say bye
    - time set 14000

디버그: false
