name: LightStudio_Done_API
version: '${version}'
main: me.taromati.doneconnector.DoneConnector
api-version: '1.0'
commands:
  done:
    description: 후원 기능 상태를 변경.
    usage: /<command> [on|off|reconnect|reload|add|ymlreload]